language: ruby
rvm:
  — 2.7.0
before_script:
  — psql -c 'create database myapp_test;' -U postgres
  — RAILS_ENV=test bundle exec rails webpacker:compile
cache: bundler
services:
  — postgresql
addons:
  postgresql: "9.4"
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master