language: ruby
dist: bionic
rvm:
  — 2.7.0
before_script:
  — psql -c 'create database myapp_test;' -U postgres
services:
  — postgresql
addons:
  postgresql: "9.4"
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master