language: ruby
rvm:
  — 2.7.0
cache: bundler
services:
  — postgresql
addons:
  postgresql: "9.4"
jobs:
  include:
    - stage: Prepare Postgres
      script: psql -c 'create database myapp_test;' -U postgres
    - stage: install
      script: bundle install
    - stage: Test
      script: skip
      deploy:
        provider: script
        script: bash deploy.sh
